import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useAuth } from "@/hooks";
import usePageTitle from "@/hooks/usePageTitle";
function AdminDashboard() {
    usePageTitle("Admin Dashboard");
    const { user } = useAuth();
    return (_jsxs("div", { className: "table", children: [_jsx("div", { className: "table__head", children: _jsxs("div", { className: "table__row", children: [_jsx("div", { className: "table__row--cell", children: "Name" }), _jsx("div", { className: "table__row--cell", children: "Status" }), _jsx("div", { className: "table__row--cell", children: "Role" }), _jsx("div", { className: "table__row--cell", children: "Actions" })] }) }), _jsxs("div", { className: "table__row", children: [_jsxs("div", { className: "table__row--cell", "data-label": "Name", children: [_jsx("img", { src: user?.image, alt: "User Icon" }), "John Doe"] }), _jsx("div", { className: "table__row--cell", "data-label": "Status", children: _jsxs("div", { className: "status green", children: [_jsx("svg", { viewBox: "0 0 24 24", fill: "currentColor", children: _jsx("circle", { cx: "12", cy: "12", r: "10" }) }), _jsx("p", { children: "Active" })] }) }), _jsx("div", { className: "table__row--cell", "data-label": "Role", children: "Administrator" }), _jsx("div", { className: "table__row--cell", "data-label": "Actions", children: _jsxs("ul", { className: "action-btns", children: [_jsx("li", { children: _jsx("a", { href: "#", children: _jsx("svg", { viewBox: "0 0 24 24", fill: "currentColor", children: _jsx("path", { d: "M3 17.25V21h3.75L17.81 9.94l-3.75-3.75L3 17.25zM20.71 7.04a1.003 1.003 0 0 0 0-1.42l-2.34-2.34a1.003 1.003 0 0 0-1.42 0l-1.83 1.83 3.75 3.75 1.84-1.82z" }) }) }) }), _jsx("li", { className: "delete", children: _jsx("a", { href: "#", children: _jsx("svg", { viewBox: "0 0 24 24", fill: "currentColor", children: _jsx("path", { d: "M16 9v10H8V9h8m-1.5-6h-5l-1 1H5v2h14V4h-4.5l-1-1z" }) }) }) })] }) })] })] }));
}
export default AdminDashboard;
